### ISSUE TITLE
Failed at the ha-dockermon@0.0.13 start script.

### ISSUE THREAD

**Issue by eldudemeister** [philhawthorne/ha-dockermon#74]
I think there are more errors but the above jumps out. Other errors below. 
Basically I ran an update on my ubuntu server and docker updated and now I cant get the container to start. 

I've tried recreating, deleting etc. Any advice greatly recieved....

```
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! ha-dockermon@0.0.13 start: `node index.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the ha-dockermon@0.0.13 start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2020-05-19T09_44_21_577Z-debug.log,
,
> ha-dockermon@0.0.13 start /usr/src/app,
> node index.js,
,
Loading settings from /config,
events.js:137,
      throw er; // Unhandled 'error' event,
      ^,
,
Error: listen EADDRINUSE :::8126,
    at Object._errnoException (util.js:1003:13),
    at _exceptionWithHostPort (util.js:1024:20),
    at Server.setupListenHandle [as _listen2] (net.js:1366:14),
    at listenInCluster (net.js:1407:12),
    at Server.listen (net.js:1495:7),
    at Function.listen (/usr/src/app/node_modules/express/lib/application.js:618:24),
    at startServer (/usr/src/app/index.js:452:22),
    at Object.<anonymous> (/usr/src/app/index.js:448:1),
    at Module._compile (module.js:660:30),
    at Object.Module._extensions..js (module.js:671:10),
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! ha-dockermon@0.0.13 start: `node index.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the ha-dockermon@0.0.13 start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2020-05-19T09_45_23_463Z-debug.log,
,
> ha-dockermon@0.0.13 start /usr/src/app,
> node index.js,
,
Loading settings from /config,
events.js:137,
      throw er; // Unhandled 'error' event,
      ^,
,
Error: listen EADDRINUSE :::8126,
    at Object._errnoException (util.js:1003:13),
    at _exceptionWithHostPort (util.js:1024:20),
    at Server.setupListenHandle [as _listen2] (net.js:1366:14),
    at listenInCluster (net.js:1407:12),
    at Server.listen (net.js:1495:7),
    at Function.listen (/usr/src/app/node_modules/express/lib/application.js:618:24),
    at startServer (/usr/src/app/index.js:452:22),
    at Object.<anonymous> (/usr/src/app/index.js:448:1),
    at Module._compile (module.js:660:30),
    at Object.Module._extensions..js (module.js:671:10),
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! ha-dockermon@0.0.13 start: `node index.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the ha-dockermon@0.0.13 start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2020-05-19T09_46_25_225Z-debug.log,
,
> ha-dockermon@0.0.13 start /usr/src/app,
> node index.js,
,
Loading settings from /config,
events.js:137,
      throw er; // Unhandled 'error' event,
      ^,
,
Error: listen EADDRINUSE :::8126,
    at Object._errnoException (util.js:1003:13),
    at _exceptionWithHostPort (util.js:1024:20),
    at Server.setupListenHandle [as _listen2] (net.js:1366:14),
    at listenInCluster (net.js:1407:12),
    at Server.listen (net.js:1495:7),
    at Function.listen (/usr/src/app/node_modules/express/lib/application.js:618:24),
    at startServer (/usr/src/app/index.js:452:22),
    at Object.<anonymous> (/usr/src/app/index.js:448:1),
    at Module._compile (module.js:660:30),
    at Object.Module._extensions..js (module.js:671:10),
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! ha-dockermon@0.0.13 start: `node index.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the ha-dockermon@0.0.13 start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2020-05-19T09_47_27_017Z-debug.log,
```

**Comment by philhawthorne** [comment]
Ah looks like something else has already used the 8126 port on your machine, by the looks of this in your error log `EADDRINUSE`

I would take a look to see if perhaps an old hadockermon container has restarted, or maybe another service is using that port now? If so you might need to try mapping a new port for hadockermon to use with the -p flag

**Comment by eldudemeister** [comment]
Hi Phil, thanks for coming back so quickly, I've tried changing the ports but it still doesnt work and if I go to the original port (8126) it says CANNOT /GET but if I go to the new port, the page cant be displayed. Also portainer hasnt said that the original port is already in use. I'm using docker compose....I also get an error in portainer saying the logs cannot be refreshed and the logs still show the ```EADDRINUSE``` as 8126. Is there anything else I an provide to help troubleshoot?

**Comment by philhawthorne** [comment]
Are you able to provide the entry you're using for your Docker compose? And also your config yaml file for hadockermon

**Comment by eldudemeister** [comment]
Sure, docker compose is 
``` docker_mon:
   image: philhawthorne/ha-dockermon
   container_name: ha_dockermon
   network_mode: host
   restart: always
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/matt/docker/dockermon:/config
   ports:
     - 7777:8126
```
```
  - platform: rest
    resource: http://127.0.0.1:7777/container/plex
    name: Plex
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'```
It was all working before but I ran some updates on my server and it all went downhill from there.

**Comment by philhawthorne** [comment]
Aha right

So when using `network_mode: host` the `ports:` has no effect. Ha-dockermon will still try to publish on port `8126` which something else is using. 

In your ha-dockermon config file, can you add

```yaml
http:
  port: 7777
```

This will force HA-Dockermon to use the `7777` port, which should then work. See the sample file here for reference: https://github.com/philhawthorne/ha-dockermon/blob/master/config/configuration.yaml.sample

**Comment by eldudemeister** [comment]
All sorted thanks Phil!
